<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<meta name="description" content="Everest Admin Panel" />
<meta name="keywords" content="Admin, Dashboard, Bootstrap3, Sass, transform, CSS3, HTML5, Web design, UI Design, Responsive Dashboard, Responsive Admin, Admin Theme, Best Admin UI, Bootstrap Theme, Wrapbootstrap, Bootstrap" />
<meta name="author" content="Bootstrap Gallery" />
<link rel="shortcut icon" href="img/favicon.ico">
<!--<title>Everest Admin Panel</title>-->

<!-- Bootstrap CSS -->
<link href="public/css/bootstrap.css" rel="stylesheet" media="screen">


<!-- Animate CSS -->
<link href="public/css/animate.css" rel="stylesheet" media="screen">

<!-- Alertify CSS -->
<link href="public/css/alertify/alertify.core.css" rel="stylesheet">
<link href="public/css/alertify/alertify.default.css" rel="stylesheet">

<!-- Main CSS -->
<link href="public/css/main.css" rel="stylesheet" media="screen">

<!-- Datepicker CSS -->
<link rel="stylesheet" type="text/css" href="public/css/datepicker.css">

<!-- Font Awesome -->
<link href="public/fonts/font-awesome.min.css" rel="stylesheet">

<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
<![endif]-->

<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
<link href="public/css/ionicons.min.css" rel="stylesheet" />
<!-- ================== END PAGE LEVEL STYLE ================== -->

<!-- ace styles -->
<!--<link rel="stylesheet" href="public/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />-->


<!-- Bootstrap CSS -->
<link href="css/bootstrap.css" rel="stylesheet" media="screen">

<!-- Animate CSS -->
<link href="css/animate.css" rel="stylesheet" media="screen">

<!-- Alertify CSS -->
<link href="css/alertify/alertify.core.css" rel="stylesheet">
<link href="css/alertify/alertify.default.css" rel="stylesheet">

<!-- Main CSS -->
<link href="css/main.css" rel="stylesheet" media="screen">

<!-- Font Awesome -->
<link href="fonts/font-awesome.min.css" rel="stylesheet">

<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
<![endif]-->



<link rel="stylesheet" href="public/css/bootstrap-datetimepicker.min.css" />
<link rel="stylesheet" href="public/css/datepicker.min.css" />


<style type="text/css">.jqstooltip { position: absolute;left: 0px;top: 0px;visibility: hidden;background: rgb(0, 0, 0) transparent;background-color: #eb5d4f;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";color: white;font: 10px arial, san serif;text-align: left;white-space: nowrap;padding: 5px;border: 1px solid white;z-index: 10000;}.jqsfield { color: white;font: 10px arial, san serif;text-align: left;}</style>

<!--<script src="public/js/jquery.min.js"></script>-->
