 <div class="current-user">
                <div class="user-avatar animated rubberBand">
                     <?php 
                     
////                     session_start();
//                     
//                     if ( $_SESSION['genero'] == 'MASCULINO') {
                       print '<img src="public/img/user4.jpg" alt="Current User">';   
//                    }  else {
//                       print '<img src="public/img/user7.jpg" alt="Current User">'; 
//                    } ?>
                    
                    <span class="busy"></span>
                </div>
                <div class="user-name">
                    Bem-vindo 
                     <?php 
                     
//                     if ($_SESSION['genero'] == 'MASCULINO') {
                       print 'Sr. '.$_SESSION['username'];   
//                    }  else {
//                       print 'Sra. '.$_SESSION['username']; 
//                    } 
                    ?>
                   
                </div>
                <ul class="user-links">
                    <li>
                        <form method="post">
                            <button name="sair" class="btn btn-danger" title="">
                                Sair
                            <i class="fa fa-sign-out"> </i>
                        </button>
                        </form>
                            
                        
                        
<!--                        <a href="?controller=Index&action=index" title="Sair">
                            <i class="fa fa-sign-out text-danger"></i>
                        </a>-->
                    </li>
                    <li>
                        <a href="?controller=Utilizador&action=alterarPassword&codUtil=<?php print base64_encode($_SESSION['idUtilizador']); ?>" title="Alterar senha">
                            <i class="fa fa-key fa-5x text-inverse"></i>
                        </a>
                        
                    </li>
                </ul>
            </div>