<?php
session_start();
if (!isset($_SESSION['logado'])) {
    //session_destroy();
    Application::redirect("?controller=Index&action=index");
}

$_SESSION['idUtilizador'];
$_SESSION['username'];
?>

<?php
if (isset($_POST['sair'])) {
    unset($_SESSION['logado']);
    Application::redirect("?controller=Index&action=index");
}

$params = $this->getParams();
$matricula = $params['dados'];
$aluno = $params['dados1'];
$classe = $params['dados2'];
$pessoa = $params['dados3'];
$dados5 = $params['dados5'];

//print_r($aluno);
//            die();                                                              
?>

<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:42:29 GMT -->
    <head>

        <?php
        include 'includes/cabecalho.phtml';
        ?>
    </head>  

    <body>
        <?php
        include 'includes/titlo.phtml';
        ?>

        <!-- Left sidebar starts -->
        <aside id="sidebar">

            <!-- Current User Starts -->
            <?php
            include 'includes/cabecalho_menu.phtml';
            ?>
            <!-- Current User Ends -->

            <!-- Menu start -->

            <?php
            include 'includes/menu.phtml';
            ?>

            <!-- Menu End -->


        </aside>
        <!-- Left sidebar ends -->

        <!-- Dashboard Wrapper starts -->
        <div class="dashboard-wrapper">

            <!-- Top Bar starts -->
            <div class="top-bar">
                <?php
                include 'includes/titlo_page.phtml';
                ?>

            </div>
            <!-- Top Bar ends -->

            <!-- Main Container starts -->
            <div class="main-container">

                <!-- Container fluid Starts -->
                <div class="container-fluid">
                    <!-- Current Stats Start -->
                    <div class="current-stats">
                        <div class="row">
                            <?php
                            if ((isset($_GET['u'])) && ($_GET['u'] == md5(1))) {
                                ?>

                                <div class="alert alert-success ">
                                    <font color= "green"><i class="ace-icon fa fa-check"></i> 
                                    <?php echo "<b>Alteração da Matricula realizada com sucesso!</b>" ?> 
                                    </font>
                                    <button type="button" class="close" data-dismiss="alert">
                                        <i class="ace-icon fa fa-times"></i>
                                    </button>
                                </div>

                            <?php }if ((isset($_GET['u'])) && ($_GET['u'] == md5(2))) {
                                ?>

                                <div class="alert alert-danger ">
                                    <font color= "white"><i class="ace-icon fa fa-times"></i> 
                                    <?php echo "<b>Erro ao alterar a Matricula!</b>" ?> 
                                    </font>
                                    <button type="button" class="close" data-dismiss="alert">
                                        <i class="ace-icon fa fa-times"></i>
                                    </button>
                                </div>

                            <?php }
                            ?>
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                            </div>
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                                <br>
                                <br>
                                <br>
                                <br>
                                <b>N.º do Processo</b>
                                <br>
                                <br>
                                <div class="center-align-text">  
                                    <div class="blog-body">
                                        <form class="" method="POST">
                                            <div class="input-group">
                                                <input type="text" name="num_processo" id="" class="form-control">
                                                <span class="input-group-btn">
                                                    <input type="hidden" name="controller" value="Matricula">
                                                    <input type="hidden" name="action" value="obterMatricula">

                                                    <button name="pesquisar" title="Pesquisar Matrícula" class="btn btn-info">
                                                        <i class="fa fa-search"></i>
                                                        Procurar</button>
                                                </span>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                            </div>

                        </div>

                        <?php
                        if (isset($aluno)) {
                            ?>
                            <hr />
                            <div class="row">
                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                    <div class="blog">

                                        <div class="blog-header">
                                            <!-- Row starts -->


                                            <div class="row">
                                                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-9">
                                                    <h4 class="blog-title"><i class="fa fa-user"></i>Dados do Aluno</h4>
                                                </div>

                                                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-3">
                                                    <?php
                                                    print '<b>' . $pessoa->getFoto() . '</b>';
                                                    ?>
                                                    <img src="img/user6.jpg" alt="User" class="blog-post-user img-responsive">
                                                </div>
                                            </div>
                                            <!-- Row ends -->
                                        </div>
                                        <div class="blog-body">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            NOME COMPLETO:
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            DATA DE NASCIMENTO:
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            GENERO:
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            NATURALIDADE:
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            B.I/C.P N.º:
                                                        </span>
                                                    </p>
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            NOME DO PAI:
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            NOME DA MÃE:
                                                        </span>
                                                    </p> 
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            TELEFONE:
                                                        </span>
                                                    </p> 


                                                </div>
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            <?php
                                                            print '<b>' . $pessoa->getNome() . ' ' . $pessoa->getSobrenome() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class=""> 
                                                            <?php
                                                            print '<b>' . date("d/m/Y", strtotime($pessoa->getData_nascim())) . '</b>';
                                                            ?>
                                                        </span>
                                                    </p>   
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class=""> 
                                                            <?php
                                                            print '<b>' . $pessoa->getGenero() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p>   
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class=""> 
                                                            <?php
                                                            print '<b>' . $pessoa->getNaturalidade() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p>   
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            <?php
                                                            print '<b>' . $pessoa->getBi_cp() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            <?php
                                                            print '<b>' . $pessoa->getNome_pai() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            <?php
                                                            print '<b>' . $pessoa->getNome_mae() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                        <span class="">
                                                            <?php
                                                            print '<b>' . $pessoa->getTelefone() . '</b>';
                                                            ?>
                                                        </span>
                                                    </p> 


                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="blog">

                                                <div class="blog-header">
                                                    <!-- Row starts -->


                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-9 col-sm-8 col-xs-9">
                                                            <h4 class="blog-title"><i class="fa fa-book"></i>Dados actuais  da Matrícula</h4>
                                                        </div>
                                                    </div>
                                                    <!-- Row ends -->
                                                </div>
                                                <div class="blog-body">    
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">

                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    CLASSE: 
                                                                </span>
                                                            </p> 
                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    ANO LECTIVO:
                                                                </span>
                                                            </p> 
                                                        </div>
                                                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    <?php
                                                                if ($classe->getDesignacao() == 'Pre-Escolar') {
                                                                    print 'Pré-Escolar';
                                                                } else {
                                                                    print $classe->getDesignacao() . 'ª Classe';
                                                                }
                                                                ?>
                                                                </span>
                                                            </p> 

                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    <?php
                                                                    print $matricula->getAno_lectivo();
                                                                    ?>
                                                                </span>
                                                            </p>   
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                        <div class="blog">

                                            <div class="blog-header">
                                                <!-- Row starts -->


                                                <div class="row">
                                                    <div class="col-lg-9 col-md-9 col-sm-8 col-xs-9">
                                                        <h4 class="blog-title"><i class="fa fa-pencil"></i>Dados da Nova Matrícula</h4>
                                                    </div>
                                                </div>
                                                <!-- Row ends -->
                                            </div>
                                            <div class="blog-body">
                                                <form class="" method="POST">
                                                    <input type="hidden" name="idAluno" value="<?php print $aluno->getId(); ?>">
                                                    <input type="hidden" name="idMatricula" value="<?php print $matricula->getId(); ?>">
                                                    <input type="hidden" name="cod_aluno" value="<?php print $aluno->getCod_aluno(); ?>">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">

                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    CLASSE: 
                                                                </span>
                                                            </p> 
                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <span class="">
                                                                    ANO LECTIVO:
                                                                </span>
                                                            </p> 

                                                        </div>
                                                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <select class="form-control" name="idClasse" data-bv-field="genero">
                                                                    <?php
                                                                    foreach ($dados5 as $classes):
                                                                        ?>
                                                                        <option class="blockquote-reverse" value="<?php print $classes->getId(); ?>">

                                                                            <?php
                                                                            if ($classes->getDesignacao() == 'Pre-Escolar') {
                                                                                print 'Pré-Escolar';
                                                                            } else {
                                                                                print $classes->getDesignacao() . 'ª Classe';
                                                                            }
                                                                            ?>
                                                                        </option>
                                                                        <?php
                                                                    endforeach;
                                                                    ?>
                                                                </select><i class="form-control-feedback" data-bv-icon-for="genero" style="display: none;"></i>
                                                                <small class="help-block" data-bv-validator="notEmpty" data-bv-for="genero" data-bv-result="NOT_VALIDATED" style="display: none;">The genre is required</small>
                                                            </p> 

                                                            <p class="left-align-text" style="font-size: 14px;" >
                                                                <select class="form-control" name="ano_lectivo" data-bv-field="genero">

                                                                    <option >
                                                                        <?php
                                                                        print date("Y");
                                                                        ?>
                                                                    </option>
                                                                    <option>
                                                                        <?php
                                                                        print date("Y") + 1;
                                                                        ?>
                                                                    </option>

                                                                </select><i class="form-control-feedback" data-bv-icon-for="genero" style="display: none;"></i>
                                                                <small class="help-block" data-bv-validator="notEmpty" data-bv-for="genero" data-bv-result="NOT_VALIDATED" style="display: none;">The genre is required</small>
                                                            </p>   
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                                                            <p>
                                                                <span>

                                                                </span>
                                                            </p>

                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">

                                                            <p class="right-align-text">
                                                                <span >
                                                                    <input type="hidden" name="controller" value="Matricula">
                                                                    <input type="hidden" name="action" value="alterar">
                                                                    <button name="enviar" class="btn btn-success btn-rounded">
                                                                        <i class="fa fa-refresh"></i>
                                                                        <b>CONCLUIR</b> 
                                                                    </button>
                                                                </span>
                                                            </p>

                                                        </div>
                                                    </div>
                                                </form>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    <?php } ?>
                </div>
                <!-- Current Stats End -->
                <!-- Spacer starts -->
                <div class="spacer">


                </div>
                <!-- Spacer ends -->

            </div>
            <!-- Container fluid ends -->
        </div>
        <!-- Main Container ends -->


        <?php
        include 'includes/rodape.phtml';
        ?>
    </body>

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:43:48 GMT -->
</html>