<?php
session_start();
if (!isset($_SESSION['logado'])) {
    //session_destroy();
    Application::redirect("?controller=Index&action=index");
}

$_SESSION['idUtilizador'];
$_SESSION['username'];

?>

<?php if (isset($_POST['sair'])) {
     unset($_SESSION['logado']);
     Application::redirect("?controller=Index&action=index");
}

$params = $this->getParams();
//$matricula = $params['dados'];
$aluno = $params['dados1'];
$classe = $params['dados2'];
$pessoa = $params['dados3'];
$morada = $params['dados4'];

//            print_r($pessoa);
//            die();                                                              


?>

<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:42:29 GMT -->
    <head>

        <?php
        include 'includes/cabecalho.phtml';
        ?>
    </head>  

    <body>
        <?php
        include 'includes/titlo.phtml';
        ?>

        <!-- Left sidebar starts -->
        <aside id="sidebar">

            <!-- Current User Starts -->
            <?php
        include 'includes/cabecalho_menu.phtml';
        ?>
            <!-- Current User Ends -->

            <!-- Menu start -->
            
                <?php
                include 'includes/menu.phtml';
                ?>
          
            <!-- Menu End -->


        </aside>
        <!-- Left sidebar ends -->

        <!-- Dashboard Wrapper starts -->
        <div class="dashboard-wrapper">

            <!-- Top Bar starts -->
            <div class="top-bar">
                <?php
                include 'includes/titlo_page.phtml';
                ?>

            </div>
            <!-- Top Bar ends -->

            <!-- Main Container starts -->
            <div class="main-container">

                <!-- Container fluid Starts -->
                <div class="container-fluid">
                    <!-- Current Stats Start -->
                    <div class="current-stats">
                        <div class="row">
                            
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                  <?php
                                        if ((isset($_GET['u'])) && ($_GET['u'] == md5(1))) {
                                            ?>
                                        
                                        <div class="alert alert-success ">
                                            <font color= "green"><i class="ace-icon fa fa-check"></i> 
                                                <?php echo "<b>Dados alterados com sucesso!</b>" ?> 
                                            </font>
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                        </div>

                                        <?php }if ((isset($_GET['u'])) && ($_GET['u'] == md5(2))) {
                                            ?>
                                        
                                        <div class="alert alert-danger ">
                                            <font color= "white"><i class="ace-icon fa fa-times"></i> 
                                                <?php echo "<b>Erro ao alterar os dados do aluno!</b>" ?> 
                                            </font>
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                        </div>
                                            
                                        <?php }
                                        ?>
                            </div>
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                <br>
                                <br>
                                <br>
                                <br>
                                <b>N.º do B.I/C.P</b>
                                <br>
                                <br>
                                <div class="center-align-text">  
                                    <div class="blog-body">
                                        <form class="" method="POST">
                                        <div class="input-group">
                                            <input type="text" name="bi_cp" id="" class="form-control">
                                            <span class="input-group-btn">
                                                <input type="hidden" name="controller" value="Aluno">
                                                <input type="hidden" name="action" value="pesquisarDado">

                                                <button name="confirmar" title="Confirmar Matrícula" class="btn btn-info">
                                                    <i class="fa fa-search"></i>
                                                    Procurar</button>
                                            </span>
                                        </div>
                                        
                                        
                                        </form>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                        <?php   
                        if (isset($aluno)) {
                            ?>
                        <hr />
                     <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="blog">
                                
                                <div class="blog-header">
                                    <h5 class="blog-title"><i class="fa fa-user"></i> DADOS DO ALUNO</h5>
                                </div>
                                                                   
                                
                                <div class="blog-body">
                                    <form id="movieForm" name="formAlteraAluno" action="" method="post" novalidate="novalidate" class="bv-form">
                                        <!--<input type="hidden" name="idAluno" value="<?php //   print $aluno->getId(); ?>">-->
                                        <input type="hidden" name="cod_aluno" value="<?php   print $aluno->getCod_aluno(); ?>">
                                        <input type="hidden" name="idMorada" value="<?php   print $morada->getId(); ?>">
                                        <input type="hidden" name="idPessoa" value="<?php   print $pessoa->getId(); ?>">
                                        <div class="form-group has-feedback">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label class="control-label">Nome</label>
                                                    <input type="text" class="form-control" name="nome" value="<?php print $pessoa->getNome(); ?>" required="true" data-bv-field="nome"><i class="form-control-feedback" data-bv-icon-for="title" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title must be less than 200 characters long</small>
                                                </div>
                                                <div class="col-md-4">
                                                    <label class="control-label">Sobrenome</label>
                                                    <input type="text" class="form-control" name="sobrenome" value="<?php print $pessoa->getSobrenome(); ?>" required="true" data-bv-field="sobrenome"><i class="form-control-feedback" data-bv-icon-for="title" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title must be less than 200 characters long</small>
                                                </div>
                                                <div class="col-md-4 selectContainer">
                                                    <label class="control-label">Genero</label>
                                                    <select class="form-control" name="genero" data-bv-field="genero">
                                                        <option selected="true" disabled="true"  ><?php print $pessoa->getGenero(); ?></option>
                                                        <option>MASCULINO</option>
                                                        <option>FEMININO</option>

                                                    </select><i class="form-control-feedback" data-bv-icon-for="genero" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="genero" data-bv-result="NOT_VALIDATED" style="display: none;">The genre is required</small>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group has-feedback">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label class="control-label">Nome do pai</label>
                                                    <input type="text" class="form-control"  name="nome_pai" value="<?php print $pessoa->getNome_pai(); ?>" required="true" data-bv-field="nome"><i class="form-control-feedback" data-bv-icon-for="title" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title must be less than 200 characters long</small>
                                                </div>
                                                <div class="col-md-4">
                                                    <label class="control-label">Nome da mãe</label>
                                                    <input type="text" class="form-control" name="nome_mae" value="<?php print $pessoa->getNome_mae(); ?>" required="true" data-bv-field="sobrenome"><i class="form-control-feedback" data-bv-icon-for="title" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="title" data-bv-result="NOT_VALIDATED" style="display: none;">The title must be less than 200 characters long</small>
                                                </div>
                                                 <div class="col-md-4">
                                                    <label class="control-label">N° B.I/C.P</label>
                                                    <input type="text" id="" class="form-control" name="bi_cp" value="<?php print $pessoa->getBi_cp(); ?>" required="true" data-bv-field="bi_cp"><i class="form-control-feedback" data-bv-icon-for="num_bi" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="bi_cp" data-bv-result="NOT_VALIDATED" style="display: none;">The director name is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="num_bi" data-bv-result="NOT_VALIDATED" style="display: none;">The director name must be less than 80 characters long</small>
                                                 </div>
                                                
                                            </div>
                                        </div>
                                        <div class="form-group has-feedback">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label class="control-label">Naturalidade</label>
                                                    <input type="text" class="form-control" name="naturalidade" value="<?php print $pessoa->getNaturalidade(); ?>"  required="true" data-bv-field="naturalidade"><i class="form-control-feedback" data-bv-icon-for="naturalidade" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="naturalidade" data-bv-result="NOT_VALIDATED" style="display: none;">The writer name is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="naturalidade" data-bv-result="NOT_VALIDATED" style="display: none;">The writer name must be less than 80 characters long</small></div>
                                                <div class="col-md-4">
                                                    <label class="control-label">Data de Nascimento</label>
                                                    <div class="input-group">

                                                    <input type="text" class="form-control  input-mask-date" name="data_nascim" value="<?php print $pessoa->getData_nascim(); ?>" data-date-format="yyyy-mm-dd" required="true" data-bv-field="data_nascim"><i class="form-control-feedback" data-bv-icon-for="data_nascim" style="display: none;"></i>
                                                    <span class="input-group-addon">
                                                <i class="fa fa-calendar bigger-110"></i>
                                            </span>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="data_nascim" data-bv-result="NOT_VALIDATED" style="display: none;">The producer name is required</small><small class="help-block" data-bv-validator="stringLength" data-bv-for="data_nascim" data-bv-result="NOT_VALIDATED" style="display: none;">The producer name must be less than 80 characters long</small>
                                                </div>
                                                </div>
                                                 <div class="col-md-4">
                                                    <label class="control-label">Telefone</label>
                                                    <input type="text" id="telefone" class="form-control" name="telefone" value="<?php print $pessoa->getTelefone(); ?>" required="true" data-bv-field="website"><i class="form-control-feedback" data-bv-icon-for="telefone" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="telefone" data-bv-result="NOT_VALIDATED" style="display: none;">The website address is required</small><small class="help-block" data-bv-validator="uri" data-bv-for="telefone" data-bv-result="NOT_VALIDATED" style="display: none;">The website address is not valid</small></div>
                                                
                                            </div>
                                        </div>
                                        <div class="form-group has-feedback">
                                            <div class="row">
                                               <div class="col-md-3">
                                                    <label class="control-label">Município</label>
                                                    <input type="text" class="form-control" name="municipio"  value="<?php print $morada->getMunicipio(); ?>" required="true" data-bv-field="bairro"><i class="form-control-feedback" data-bv-icon-for="bairro" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="municipio" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is required</small><small class="help-block" data-bv-validator="uri" data-bv-for="bairro" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is not valid</small>
                                                </div>
                                               <div class="col-md-3">
                                                    <label class="control-label">Bairro</label>
                                                    <input type="text" class="form-control" name="bairro" value="<?php print $morada->getBairro(); ?>" required="true" data-bv-field="bairro"><i class="form-control-feedback" data-bv-icon-for="bairro" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="bairro" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is required</small><small class="help-block" data-bv-validator="uri" data-bv-for="bairro" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is not valid</small>
                                                </div>
                                                <div class="col-md-3">
                                                    <label class="control-label">Rua</label>
                                                    <input type="text" class="form-control" name="rua" value="<?php print $morada->getRua(); ?>" required="true" data-bv-field="rua"><i class="form-control-feedback" data-bv-icon-for="rua" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="rua" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is required</small><small class="help-block" data-bv-validator="uri" data-bv-for="rua" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is not valid</small>
                                                </div>
                                                <div class="col-md-3">
                                                    <label class="control-label">N° da Casa</label>
                                                    <input type="text" class="form-control" name="num_casa" value="<?php print $morada->getNum_casa(); ?>" required="true" data-bv-field="num_casa"><i class="form-control-feedback" data-bv-icon-for="num_casa" style="display: none;"></i>
                                                    <small class="help-block" data-bv-validator="notEmpty" data-bv-for="num_casa" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is required</small><small class="help-block" data-bv-validator="uri" data-bv-for="num_casa" data-bv-result="NOT_VALIDATED" style="display: none;">The trailer link is not valid</small>
                                                </div>
                                            </div>
                                        </div>

                                     <div class="form-group has-feedback">

                                            <input type="hidden" name="controller" value="Aluno">
                                            <input type="hidden" name="action" value="alterar">
                                            <button type="submit" class="btn btn-primary btn-rounded" onclick="return validarForm()">
                                                <i class="fa fa-refresh"></i>
                                                CONCLUIR</button>
                                            <button type="reset" class="btn btn-default btn-rounded">
                                                <i class="fa fa-undo"></i>
                                                LIMPAR</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Current Stats End -->
                    <!-- Spacer starts -->
                    <div class="spacer">

                        
                    </div>
                    <!-- Spacer ends -->

                </div>
                <!-- Container fluid ends -->
            </div>
            <!-- Main Container ends -->

            
            <?php
            include 'includes/rodape.phtml';
            ?>
    </body>

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:43:48 GMT -->
</html>