<?php
session_start();
if (!isset($_SESSION['logado'])) {
    //session_destroy();
    Application::redirect("?controller=Index&action=index");
}

$_SESSION['idUtilizador'];
$_SESSION['username'];
//var_dump($_SESSION['genero']);
//die();
?>

<?php
if (isset($_POST['sair'])) {
    unset($_SESSION['logado']);
    Application::redirect("?controller=Index&action=index");
}
?>

<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:42:29 GMT -->
    <head>

        <?php
        include 'includes/cabecalho.phtml';
        ?>
        <!--        <link href="public/css/bootstrap.min.css" rel="stylesheet" media="screen">
                
                <script src="public/js/jquery.min.js" lang="javascript" type="text/javascript"></script>
                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->

    </head>  

    <body>
        <?php
        include 'includes/titlo.phtml';
        ?>

        <!-- Left sidebar starts -->
        <aside id="sidebar">

            <!-- Current User Starts -->
            <?php
            include 'includes/cabecalho_menu.phtml';
            ?>
            <!-- Current User Ends -->

            <!-- Menu start -->

            <?php
            include 'includes/menu.phtml';
            ?>

            <!-- Menu End -->


        </aside>
        <!-- Left sidebar ends -->

        <!-- Dashboard Wrapper starts -->
        <div class="dashboard-wrapper">

            <!-- Top Bar starts -->
            <div class="top-bar">
                <?php
                include 'includes/titlo_page.phtml';
                ?>

            </div>
            <!-- Top Bar ends -->

            <!-- Main Container starts -->
            <div class="main-container">

                <!-- Container fluid Starts -->
                <div class="container-fluid">
                    <!-- Current Stats Start -->
                    <div class="current-stats">
                        <div class="row">
                            <?php if ($_SESSION['funcao'] === "DIRECTOR") { ?>



                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">  

                                        <a class="btn btn-default btn-rounded" href="?controller=Funcionario&action=registar">
                                            <i class="fa fa-user fa-5x"></i>
                                            <font color=#4e6f94>
                                            Cadastrar <br>Funcionário
                                            </font></a>


                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a  class="btn btn-info btn-rounded" href="?controller=Funcionario&action=listar">
                                            <i class="fa fa-users fa-5x"></i>
                                            <font color=#ffffff>
                                            Listar <br>Funcionários
                                            </font></a>

                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <div class=" center-align-text">  
                                        <hr />
                                        <a class="btn btn-default btn-rounded" href="?controller=Utilizador&action=registar">
                                            <i class="fa fa-user fa-5x"></i>
                                            <font color=#4e6f94>
                                            Cadastrar <br>Utilizador
                                            </font></a>


                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a  class="btn btn-info btn-rounded" href="?controller=Utilizador&action=listar">
                                            <i class="fa fa-users fa-5x"></i>
                                            <font color=#ffffff>
                                            Listar <br>Utilizadores
                                            </font></a>

                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class=" center-align-text">  
                                        <a class="btn btn-default btn-rounded" href="?controller=Cliente&action=registar">
                                            <i class="fa fa-user fa-5x"></i>
                                            <font color=#4e6f94>
                                            Cadastrar <br>Cliente
                                            </font>
                                        </a>
                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a  class="btn btn-info btn-rounded" href="?controller=Cliente&action=listar">
                                            <i class="fa fa-users fa-5x"></i>
                                            <font color=#ffffff>
                                            Listar <br>Clientes
                                            </font></a>

                                    </div>
                                    <hr />
                                </div>

                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-default btn-rounded"  href="?controller=Cliente&action=listarClientes">
                                            <i class="fa fa-money fa-5x"></i>
                                            <font color=#4e6f94>
                                            Registar <br>Pagamento
                                            </font></a>

                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-primary btn-rounded"  href="?controller=Pagamento&action=listar">
                                            <i class="fa fa-eye fa-5x"></i>
                                            <font color=#ffffff>
                                            Ver todos <br>os pagamentos
                                            </font></a>

                                    </div>
                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-danger btn-rounded"  href="?controller=Pagamento&action=listarMovimento">
                                            <font color="white">
                                            <i class="fa fa-eye fa-5x"></i> 
                                            <span>Ver <br>pagamentos do dia</span></font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-warning btn-rounded"  href="?controller=Pagamento&action=listarMovimentoMensal">
                                            <font color="white">
                                            <i class="fa fa-eye fa-5x"></i> 
                                            <span>Ver <br>pagamentos do mês</span></font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-default btn-rounded"  href="?controller=Pagamento&action=listarPagamentoPorMes">
                                            <font color=#4e6f94>
                                            <i class="fa fa-search fa-5x"></i> 
                                            <span>Pesquisar <br>pagamentos por mês</span></font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                                    <hr />
                                    <div class="center-align-text">

                                        <a class="btn btn-linkedin btn-rounded"  href="?controller=Pagamento&action=listarPagamentoPeloDia">
                                            <font color=#ffffff>
                                            <i class="fa fa-search fa-5x"></i> 
                                            <span>Pesquisar <br>pagamentos pelo dia</span></font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>
                            <?php } if ($_SESSION['funcao'] == 'SUBD.ADMINISTRATIVO' || $_SESSION['funcao'] == 'SEC.ADMINISTRATIVO') { ?>

                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">

                                    <div class="center-align-text">
                                        <a class="btn btn-primary btn-rounded" href="?controller=Matricula&action=registar">
                                            <i class="fa fa-book fa-5x"></i> 
                                            <font color="white">
                                            <b>Registar <br>Matrícula</b>
                                            </font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                    <div class="center-align-text">
                                        <a class="btn btn-warning btn-rounded"  href="?controller=Matricula&action=pesquisarMatricula">
                                            <i class="fa fa-search fa-5x"></i> 
                                            <font color="white">
                                            <b>Consultar <br>Matrícula</b>
                                            </font>
                                        </a>

                                    </div>
                                    <hr />
                                </div>

                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                    <div class="center-align-text">

                                        <a class="btn btn-linkedin btn-rounded"  href="?controller=Matricula&action=alterarMatricula">

                                            <i class="fa fa-pencil fa-5x"></i> 
                                            <font color="white">
                                            <b>Alterar &nbsp;&nbsp;&nbsp;<br>Matrícula</b>
                                            </font>
                                        </a>

                                    </div>

                                    <hr />
                                </div>

                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <div class="center-align-text">

                                            <a class="btn btn-danger btn-rounded"  href="?controller=Matricula&action=confirmarMatricula">

                                                <i class="fa fa-refresh fa-5x"></i> 
                                                <font color="white">
                                                <b>Confirmar <br>Matrícula</b>
                                                </font>
                                            </a>
                                        </div>

                                        <hr />
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <div class="center-align-text">
                                            <a class="btn btn-primary btn-rounded"  href="?controller=Aluno&action=alterarDados">

                                                <i class="fa fa-pencil fa-5x"></i> 
                                                <font color="white">
                                                <b>Alterar dados <br> do Aluno</b>
                                                </font>
                                            </a>
                                        </div>
                                        <hr />
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <div class="center-align-text">
                                            <a class="btn btn-warning btn-rounded"  href="?controller=Aluno&action=consultarDados">

                                                <i class="fa fa-search fa-5x"></i> 
                                                <font color="white">
                                                <b>Consultar <br>Aluno</b>
                                                </font>
                                            </a>
                                        </div>
                                        <hr />
                                    </div>

                                </div>
                            </div>
                        <?php
                        } if ($_SESSION['funcao'] == 'FINANCA') { ?>
                             <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <hr />
                                        <div class="center-align-text">

                                            <a class="btn btn-danger btn-rounded"  href="?controller=Pagamento_Propina&action=registar">

                                                <i class="fa fa-money fa-5x"></i> 
                                                <font color="white">
                                                <b>Registar<br>Pagamento de Propina</b>
                                                </font>
                                            </a>
                                        </div>

                                        <hr />
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <hr />
                                        <div class="center-align-text">
                                            <a class="btn btn-primary btn-rounded"  href="?controller=Pagamento_propina&action=listar">

                                                <i class="fa fa-list fa-5x"></i> 
                                                <font color="white">
                                                <b>Listar todos <br>os Pagamentos</b>
                                                </font>
                                            </a>
                                        </div>
                                        <hr />
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <hr />
                                        <div class="center-align-text">
                                            <a class="btn btn-warning btn-rounded"  href="">

                                                <i class="fa fa-search fa-5x"></i> 
                                                <font color="white">
                                                <b>Ver pagamentos <br>do dia</b>
                                                </font>
                                            </a>
                                        </div>
                                        <hr />
                                    </div>

                                </div>
                        <?php } ?>


                    </div>
                </div>
                <!-- Current Stats End -->
                <!-- Spacer starts -->
                <div class="spacer">


                </div>
                <!-- Spacer ends -->

            </div>
            <!-- Container fluid ends -->
        </div>
        <!-- Main Container ends -->

        <script src="../public/js/bootstrap.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $('#pesMatriculaModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var recipient = button.data('whatever') // Extract info from data-* attributes
                var recipientnome = button.data('whatevernome')
                var recipientdetalhes = button.data('whateverdetalhes')
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title').text('ID do Curso: ' + recipient)
                modal.find('#id_curso').val(recipient)
                modal.find('#recipient-name').val(recipientnome)
                modal.find('#detalhes-text').val(recipientdetalhes)
            })
        </script>
        <?php
        include 'includes/rodape.phtml';
        ?>
    </body>

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:43:48 GMT -->
</html>