<!DOCTYPE html>
<html lang="en">
	
<!-- Mirrored from jesus.gallery/everest/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:45:00 GMT -->
<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<meta name="description" content="Everest Admin Panel" />
		<meta name="keywords" content="Admin, Dashboard, Bootstrap3, Sass, transform, CSS3, HTML5, Web design, UI Design, Responsive Dashboard, Responsive Admin, Admin Theme, Best Admin UI, Bootstrap Theme, Wrapbootstrap, Bootstrap" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="shortcut icon" href="img/favicon.ico">
		<title>SGE-MM | Login </title>
		
		<!-- Bootstrap CSS -->
		<link href="public/css/bootstrap.css" rel="stylesheet" media="screen">

		<!-- Animate CSS -->
		<link href="public/css/animate.css" rel="stylesheet" media="screen">

		<!-- Main CSS -->
		<link href="public/css/main.css" rel="stylesheet" media="screen">

		<!-- Main CSS -->
		<link href="public/css/login.css" rel="stylesheet">

		<!-- Font Awesome -->
		<link href="public/fonts/font-awesome.min.css" rel="stylesheet">

		<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->

	</head>  

	<body>
		<!-- Container Fluid starts -->
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-push-4 col-md-4 col-sm-push-3 col-sm-6 col-sx-12">
					
					<!-- Header end -->
					<div class="login-container">
						<div class="login-wrapper animated flipInY">
							<div id="login" class="show">
								<div class="login-header bigger">
                                                                    <i class="fa fa-lock fa-2x"></i>
									Faça o seu Login
								</div>
                                                              <?php
                                                                                    if ((isset($_GET['u'])) && ($_GET['u'] == md5(1))) {
                                                                                        ?>
                                                            <font color= "Red" style="size:16;"> 
                                                            <script type="text/javascript">
                                                            alert('Utilizador e/ou Senha incorretos');
                                                            </script> 
                                                                
                                                                <?php ?> </font>
                                                                                    <?php } ?>
                                                            <form action="" method="post" name="formUtilizador">
									<div class="form-group has-feedback">
										<label class="control-label" for="username">Utilizador</label>
                                                                                <input type="text" class="form-control" name="username" id="userName" placeholder="" autofocus>
										<i class="fa fa-user text-info form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label class="control-label" for="password">Senha</label>
                                                                                <input type="password" name="password" class="form-control" id="passWord" placeholder="" >
										<i class="fa fa-key text-danger form-control-feedback"></i>
									</div>
                                                                    <div class="login-buttons">
                                                                        <input type="hidden" name="controller" value="Utilizador">
                                                                        <input type="hidden" name="action" value="logar">
                                                                        <button type="submit" name="enviar" class="btn btn-primary btn-block btn-lg" onclick="return validarForm()">
                                                                            Entrar
                                                                            
                                                                                <i class="fa fa-sign-in"></i>
                                                                         
                                                                        </button>
                                                                    </div>
								</form>
								
							</div>

							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Container Fluid ends -->
		
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="js/jquery.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="js/bootstrap.min.js"></script>
                
                
                
                <script language="javascript" type="text/javascript">
        function validarForm() {
            var username = formUtilizador.username.value;
            var password = formUtilizador.password.value;
           
            if (username == "" && password == "") {
                alert('Os campos estão vazios!');
                formUtilizador.username.focus();
                return false;
            }
            if (password == "") {
                alert('Preencha o campo Senha');
                formUtilizador.password.focus();
                return false;
            }
            if (username == "") {
                alert('Preencha o campo Utilizador');
                formUtilizador.username.focus();
                return false;
            }
           
        }
                </script>

              

		<script type="text/javascript">
			(function($) {
				// constants
				var SHOW_CLASS = 'show',
					HIDE_CLASS = 'hide',
					ACTIVE_CLASS = 'active';
				
				$('a').on('click', function(e){
					e.preventDefault();
					var a = $(this),
					href = a.attr('href');
				
					$('.active').removeClass(ACTIVE_CLASS);
					a.addClass(ACTIVE_CLASS);

					$('.show')
					.removeClass(SHOW_CLASS)
					.addClass(HIDE_CLASS)
					.hide();
					
					$(href)
					.removeClass(HIDE_CLASS)
					.addClass(SHOW_CLASS)
					.hide()
					.fadeIn(550);
				});
			})(jQuery);
		</script>
	</body>

<!-- Mirrored from jesus.gallery/everest/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:45:01 GMT -->
</html>