<html lang="en"><!-- Mirrored from jesus.gallery/everest/error.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:45:11 GMT --><head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Everest Admin Panel">
        <meta name="keywords" content="Admin, Dashboard, Bootstrap3, Sass, transform, CSS3, HTML5, Web design, UI Design, Responsive Dashboard, Responsive Admin, Admin Theme, Best Admin UI, Bootstrap Theme, Wrapbootstrap, Bootstrap">
        <meta name="author" content="Bootstrap Gallery">
        <link rel="shortcut icon" href="img/favicon.ico">
        <title>Flat Metro Dashboard</title>
        
        <!-- Bootstrap CSS -->
        <link href="public/css/bootstrap.css" rel="stylesheet" media="screen">

        <!-- Main CSS -->
        <link href="public/css/main.css" rel="stylesheet" media="screen">

        <!-- Font Awesome -->
        <link href="public/fonts/font-awesome.min.css" rel="stylesheet">

        <!-- Font Awesome -->
        <link href="public/css/error.css" rel="stylesheet" media="screen">

        <!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
            <script src="js/respond.min.js"></script>
        <![endif]-->

    </head>  

    <body>

        <div id="page-wrapper">
            <div class="error center-align-text">
                <h1 class="error-heading">404<i>!</i></h1>
                <h2 class="text-danger">Oops</h2>
                <h3><i class="ace-icon fa fa-sitemap"></i> Página não encontrada!</h3>
                <h5>Tente uma das seguintes opções:</h5>
                 <ul class="list-unstyled spaced inline bigger-110 margin-15">
                                                <li>
                                                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                                                    Certifique-se de que a data esteja correcta.
                                                </li>

                                                <li>
                                                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                                                    Certifique-se de que não tenha apagado indevidamente um determinado ficheiro do servidor.
                                                </li>

                                                <li>
                                                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                                                    Contacte o serviço de apoio.
                                                </li>
                                            </ul>
                                           
                <a href="?controller=Index&action=index" class="btn btn-success">Voltar &agrave; tela de login</a>
            </div>       
        </div>

    

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="public/js/jquery.js"></script>

        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="public/js/bootstrap.min.js"></script>
        
    

<!-- Mirrored from jesus.gallery/everest/error.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:45:11 GMT -->
</body></html>