<?php
session_start();
if (!isset($_SESSION['logado'])) {
    //session_destroy();
    Application::redirect("?controller=Index&action=index");
}

$_SESSION['idUtilizador'];
$_SESSION['username'];

?>

<?php if (isset($_POST['sair'])) {
     unset($_SESSION['logado']);
     Application::redirect("?controller=Index&action=index");
}

$params = $this->getParams();
$matricula = $params['dados'];
$aluno1 = $params['dados1'];
$classe = $params['dados2'];
$pessoa = $params['dados3'];
$morada = $params['dados4'];

            //print_r($retorno3);
            //die();                                                              

?>

<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:42:29 GMT -->
    <head>

        <?php
        include 'includes/cabecalho.phtml';
        ?>
<!--        <link href="public/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <script src="public/js/bootstrap.min.js"></script>
	<script src="public/js/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->
    </head>  

    <body>
        <?php
        include 'includes/titlo.phtml';
        ?>

        <!-- Left sidebar starts -->
        <aside id="sidebar">

            <!-- Current User Starts -->
            <?php
        include 'includes/cabecalho_menu.phtml';
        ?>
            <!-- Current User Ends -->

            <!-- Menu start -->
            
                <?php
                include 'includes/menu.phtml';
                ?>
          
            <!-- Menu End -->


        </aside>
        <!-- Left sidebar ends -->

        <!-- Dashboard Wrapper starts -->
        <div class="dashboard-wrapper">

            <!-- Top Bar starts -->
            <div class="top-bar">
                <?php
                include 'includes/titlo_page.phtml';
                ?>

            </div>
            <!-- Top Bar ends -->

            <!-- Main Container starts -->
            <div class="main-container">

                <!-- Container fluid Starts -->
                <div class="container-fluid">
                    <!-- Current Stats Start -->
                    <div class="current-stats">
                        <div class="row">
                            
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                <?php
                                        if ((isset($_GET['u'])) && ($_GET['u'] == md5(1))) {
                                            ?>
                                        
                                        <div class="alert alert-success ">
                                            <font color= "green"><i class="ace-icon fa fa-check"></i> 
                                                <?php echo "<b>Nenhum resultado encontrado!</b>" ?> 
                                            </font>
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                        </div>

                                        <?php }?>
                            </div>
                            <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
                                <br>
                                <br>
                                <br>
                                <br>
                                <b>Digite o N.º do Processo</b>
                                <br>
                                <br>
                                <div class="center-align-text">  
                                    <div class="blog-body">
                                        <form class="" method="POST" name="formPesq">
                                        <div class="input-group">
                                            <input type="text" name="num_processo" placeholder="Ex:000000654LA041/2021" id="" size="55" class="form-control col-sm-8">
                                            <span class="input-group-btn">
                                                <input type="hidden" name="controller" value="Matricula">
                                                <input type="hidden" name="action" value="obterMatriculaProcesso">

                                                <button name="pesquisar" title="Pesquisar Matrícula" class="btn btn-info" onclick="return verificarForm();">
                                                    <i class="fa fa-search"></i>
                                                    Procurar</button>
                                            </span>
                                        </div>
                                        
                                        
                                        </form>
                                    </div>
                                </div>
                            </div>
                            
                            <script src="../../public/js/jquery.js"></script>
                            <!-- Include all compiled plugins (below), or include individual files as needed -->
                            <script src="../../public/js/bootstrap.min.js"></script>
                            <script type="text/javascript" language="javascript">
                                function verificarForm(){
                                var num_proc = formPesq.num_processo.value;
                                    if(num_proc == ""){
                                        alert("Digite o número do processo!");
                                        formPesq.num_processo.focus();
                                        return false;
                                    }
                                }
                            </script>
                            
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                               
                            </div>
                            
                        </div>
                        
                        <?php   
                        if (isset($matricula)) {
                            ?>
                        <hr />
                            <div class="row">
                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                    <div class="blog">
                                        
                                        <div class="blog-header">
                                            <!-- Row starts -->
                                            

                                            <div class="row">
                                                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-9">
                                                    <h4 class="blog-title"><i class="fa fa-user"></i>Dados do Aluno</h4>
                                                </div>
                                                
                                                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-3">
                                                     <?php
                                                     print  '<b>'.$pessoa->getFoto().'</b>';
                                                    ?>
                                                   <img src="img/user6.jpg" alt="User" class="blog-post-user img-responsive">
                                                </div>
                                            </div>
                                            <!-- Row ends -->
                                        </div>
                                        <div class="blog-body">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    NOME COMPLETO:
                                                </span>
                                            </p> 
                                                     <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    DATA DE NASCIMENTO:
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    GENERO:
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    NATURALIDADE:
                                                </span>
                                            </p> 
                                              <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    B.I/C.P N.º:
                                                </span>
                                            </p>
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    NOME DO PAI:
                                                </span>
                                            </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    NOME DA MÃE:
                                                </span>
                                            </p> 
                                            </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    TELEFONE:
                                                </span>
                                            </p> 
                                                   
                                                   
                                                </div>
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$pessoa->getNome().' '.$pessoa->getSobrenome().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                                  <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php
                                                     print  '<b>'.date("d/m/Y", strtotime($pessoa->getData_nascim())).'</b>';
                                                    ?>
                                                </span>
                                            </p>   
                                                  <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php
                                                     print  '<b>'.$pessoa->getGenero().'</b>';
                                                    ?>
                                                </span>
                                            </p>   
                                                  <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php
                                                     print  '<b>'.$pessoa->getNaturalidade().'</b>';
                                                    ?>
                                                </span>
                                            </p>   
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$pessoa->getBi_cp().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$pessoa->getNome_pai().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$pessoa->getNome_mae().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$pessoa->getTelefone().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                            
                                            
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                    <div class="blog">
                                        
                                        <div class="blog-header">
                                            <!-- Row starts -->
                                            

                                            <div class="row">
                                                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-9">
                                                    <h4 class="blog-title"><i class="fa fa-book"></i>Dados da Matrícula</h4>
                                                </div>
                                                
                                               
                                            </div>
                                            <!-- Row ends -->
                                        </div>
                                        <div class="blog-body">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    N.º DO PROCESSO:
                                                </span>
                                            </p> 
                                                     <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    ANO LECTIVO:
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    CLASSE: 
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    DATA DA MATRÍCULA:
                                                </span>
                                            </p> 
                                            
                                                </div>
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$matricula->getNum_processo().'/'.$matricula->getAno_lectivo().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                                  <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php
                                                     print  '<b>'.$matricula->getAno_lectivo().'</b>';
                                                    ?>
                                                </span>
                                            </p>   
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php 
                                                            if ($classe->getDesignacao() == 'Pre-Escolar') {
                                                                print 'Pré-Escolar/Inic.';
                                                            }else{
                                                            print $classe->getDesignacao().'ª Classe';
                                                            }?>
                                                </span>
                                            </p>   
                                                  <p class="left-align-text" style="font-size: 14px;" >
                                                <span class=""> 
                                                    <?php
                                                        
                                                        $dt = explode(" ", $matricula->getData_registo());
                                                        
                                                        $data = date("d/m/Y", strtotime($dt[0]));
                                                        $hora = $dt[1];
                                                    
                                                     print  '<b>'.$data.' '.$hora.'</b>';
                                                    ?>
                                                </span>
                                            </p>   
                                                  
                                            
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                    <div class="blog">
                                        
                                        <div class="blog-header">
                                            <!-- Row starts -->
                                            

                                            <div class="row">
                                                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-9">
                                                    <h4 class="blog-title"><i class="fa fa-home"></i>DADOS DA MORADA</h4>
                                                </div>
                                            </div>
                                            <!-- Row ends -->
                                        </div>
                                        <div class="blog-body">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    MUNICÍPIO:
                                                </span>
                                            </p> 
                                                     <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    BAIRRO:
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    RUA:
                                                </span>
                                            </p> 
                                            <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                    CASA N.º:
                                                </span>
                                            </p> 
                                                </div>
                                                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$morada->getMunicipio().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$morada->getBairro().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$morada->getRua().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                                    <p class="left-align-text" style="font-size: 14px;" >
                                                <span class="">
                                                   <?php
                                                     print  '<b>'.$morada->getNum_casa().'</b>';
                                                    ?>
                                                </span>
                                            </p> 
                                               
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>


                        <?php } ?>
                    </div>
                    <!-- Current Stats End -->
                    <!-- Spacer starts -->
                    <div class="spacer">

                        
                    </div>
                    <!-- Spacer ends -->

                </div>
                <!-- Container fluid ends -->
            </div>
            <!-- Main Container ends -->

            
            <?php
            include 'includes/rodape.phtml';
            ?>
    </body>

    <!-- Mirrored from jesus.gallery/everest/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Apr 2015 10:43:48 GMT -->
</html>